#!/usr/bin/env python3
"""Generate the Nav2 map, the semantic map YAML and the Gazebo world.

All three come from `semantic_nav.demo_world`, which is the same code the unit
tests plan against. That is the point of this script: without it there are
three hand-maintained copies of one office, they drift, and the resulting bug
— tests pass, simulation fails — is close to impossible to attribute, because
nothing is wrong with any single file.

    python scripts/generate_map.py

Writes:
    src/robot_bringup/maps/office.pgm
    src/robot_bringup/maps/office.yaml
    src/robot_bringup/config/semantic_map.yaml
    src/robot_bringup/worlds/office.world
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src" / "robot_core"))
sys.path.insert(0, str(ROOT / "src" / "semantic_nav"))

from robot_core.occupancy import OCCUPIED_THRESHOLD, UNKNOWN      # noqa: E402
from semantic_nav.demo_world import (                             # noqa: E402
    HEIGHT_M,
    WIDTH_M,
    build_grid,
    build_semantic_map,
)

BRINGUP = ROOT / "src" / "robot_bringup"


def write_pgm(grid, path: Path) -> None:
    r"""Binary PGM (P5), the format nav2_map_server reads.

    Every text file this script writes passes `newline="\n"`. Without it Python
    translates newlines to CRLF on Windows, the generated files differ byte for
    byte depending on who ran the generator, and the reproducibility test fails
    on a difference nobody made. Generated artefacts are LF everywhere.

    Row order is inverted relative to the occupancy grid: PGM is written
    top-row-first while a ROS occupancy grid is indexed from the bottom-left.
    Getting this wrong produces a map that is vertically mirrored — which looks
    plausible enough that people chase it as a localisation problem for a
    while.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    pixels = bytearray()
    for row in reversed(range(grid.height)):
        for col in range(grid.width):
            value = grid.data[row * grid.width + col]
            if value == UNKNOWN:
                pixels.append(205)          # the conventional grey for unknown
            elif value >= OCCUPIED_THRESHOLD:
                pixels.append(0)            # black = occupied
            else:
                pixels.append(254)          # near-white = free
    # ASCII only. The PGM header is encoded as bytes, so a stray en-dash in
    # this comment line raises UnicodeEncodeError instead of writing a map.
    header = f"P5\n# generated by scripts/generate_map.py - do not edit\n" \
             f"{grid.width} {grid.height}\n255\n"
    path.write_bytes(header.encode("ascii") + bytes(pixels))
    print(f"wrote {path.relative_to(ROOT)}  ({grid.width}x{grid.height})")


def write_map_yaml(grid, pgm_name: str, path: Path) -> None:
    path.write_text(
        f"""# generated by scripts/generate_map.py - do not edit
image: {pgm_name}
mode: trinary
resolution: {grid.resolution}
origin: [{grid.origin_x}, {grid.origin_y}, 0.0]
negate: 0
occupied_thresh: 0.65
free_thresh: 0.25
""",
        encoding="utf-8",
        newline="\n",
    )
    print(f"wrote {path.relative_to(ROOT)}")


def write_semantic_map(semantic_map, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    semantic_map.save(path)
    text = path.read_text(encoding="utf-8")
    path.write_text(
        "# generated by scripts/generate_map.py - edit demo_world.py instead\n"
        + text,
        encoding="utf-8",
        newline="\n",
    )
    print(f"wrote {path.relative_to(ROOT)}  ({len(semantic_map)} landmarks)")


def _box(name, x0, y0, x1, y1, height=1.4):
    cx, cy = (x0 + x1) / 2, (y0 + y1) / 2
    sx, sy = abs(x1 - x0), abs(y1 - y0)
    return f"""
    <model name="{name}">
      <static>true</static>
      <pose>{cx:.3f} {cy:.3f} {height/2:.3f} 0 0 0</pose>
      <link name="link">
        <collision name="collision">
          <geometry><box><size>{sx:.3f} {sy:.3f} {height:.3f}</size></box></geometry>
        </collision>
        <visual name="visual">
          <geometry><box><size>{sx:.3f} {sy:.3f} {height:.3f}</size></box></geometry>
          <material><ambient>0.55 0.57 0.6 1</ambient>
                    <diffuse>0.65 0.67 0.7 1</diffuse></material>
        </visual>
      </link>
    </model>"""


def write_world(path: Path) -> None:
    """The same walls as `build_grid`, as Gazebo boxes.

    Kept in this script rather than hand-written so the simulation and the
    planner cannot disagree about where the walls are.
    """
    walls = [
        ("wall_south", 0.0, 0.0, WIDTH_M, 0.2),
        ("wall_north", 0.0, HEIGHT_M - 0.2, WIDTH_M, HEIGHT_M),
        ("wall_west", 0.0, 0.0, 0.2, HEIGHT_M),
        ("wall_east", WIDTH_M - 0.2, 0.0, WIDTH_M, HEIGHT_M),
        ("divider_a", 0.0, 4.9, 2.4, 5.1),
        ("divider_b", 3.6, 4.9, 8.4, 5.1),
        ("divider_c", 9.6, 4.9, WIDTH_M, 5.1),
        ("partition", 5.9, 5.1, 6.1, HEIGHT_M),
    ]
    furniture = [
        ("reception_desk", 3.4, 0.6, 5.6, 1.3, 0.75),
        ("printer_table", 9.4, 2.4, 10.2, 3.0, 0.9),
        ("meeting_table", 1.4, 6.4, 4.6, 7.6, 0.75),
    ]

    models = "".join(_box(*item) for item in walls + furniture)

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(f"""<?xml version="1.0"?>
<!-- generated by scripts/generate_map.py - edit demo_world.py instead -->
<sdf version="1.6">
  <world name="office">
    <include><uri>model://ground_plane</uri></include>
    <include><uri>model://sun</uri></include>

    <physics type="ode">
      <max_step_size>0.002</max_step_size>
      <!-- 1.0 rather than "as fast as possible". A simulation running faster
           than real time starves the control loops it is meant to be testing,
           and the resulting instability is a property of the test rig rather
           than of the robot. -->
      <real_time_factor>1.0</real_time_factor>
      <real_time_update_rate>500</real_time_update_rate>
    </physics>
{models}
  </world>
</sdf>
""", encoding="utf-8", newline="\n")
    print(f"wrote {path.relative_to(ROOT)}")


def main() -> int:
    grid = build_grid()
    semantic_map = build_semantic_map()

    write_pgm(grid, BRINGUP / "maps" / "office.pgm")
    write_map_yaml(grid, "office.pgm", BRINGUP / "maps" / "office.yaml")
    write_semantic_map(semantic_map, BRINGUP / "config" / "semantic_map.yaml")
    write_world(BRINGUP / "worlds" / "office.world")

    print(f"\n{grid.occupied_fraction():.1%} of the map is occupied; "
          f"{len(semantic_map)} landmarks")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
